export const exerciseData = [
  {
    id: "ankle",
    title: "Ankle",
    subItems: [{ id: "ankle-sprain", title: "Ankle Sprain" }],
  },
  {
    id: "cervical",
    title: "Cervical",
    subItems: [
      { id: "bulging-disc", title: "Bulging disc" },
      { id: "cervical-radiculopathy", title: "Cervical radiculopathy" },
      { id: "degenerated-disc", title: "Degenerated disc" },
      { id: "facet-syndrome", title: "Facet Syndrome" },
      { id: "forward-head-posture", title: "Forward Head Posture" },
      { id: "herniated-disc", title: "Herniated disc" },
      { id: "kyphosis", title: "Kyphosis" },
      { id: "lordosis", title: "Lordosis" },
      { id: "neck-pain", title: "Neck Pain" },
      { id: "spondylolithesis", title: "Spondylolithesis" },
      { id: "stenosis", title: "Stenosis" },
      { id: "subluxation", title: "Subluxation" },
    ],
  },
  {
    id: "elbow",
    title: "Elbow",
    subItems: [{ id: "epicondylitis", title: "Epicondylitis" }],
  },
  {
    id: "foot",
    title: "Foot",
    subItems: [
      { id: "plantar-fasciitis", title: "Plantar Fasciitis" },
      { id: "pronation", title: "Pronation" },
      { id: "supination", title: "Supination" },
    ],
  },
  {
    id: "hip",
    title: "Hip",
    subItems: [{ id: "piriformis-syndrome", title: "Piriformis Syndrome" }],
  },
  {
    id: "knee",
    title: "Knee",
    subItems: [
      { id: "acl-injury", title: "ACL Injury" },
      { id: "mcl-injury", title: "MCL Injury" },
      { id: "meniscus-tear", title: "Meniscus Tear" },
      { id: "osteoarthritis", title: "Osteoarthritis" },
    ],
  },
  {
    id: "lumbar",
    title: "Lumbar",
    subItems: [
      { id: "bulging-disc", title: "Bulging disc" },
      { id: "cervical-radiculopathy", title: "Cervical radiculopathy" },
      { id: "degenerated-disc", title: "Degenerated disc" },
      { id: "facet-syndrome", title: "Facet Syndrome" },
      { id: "forward-head-posture", title: "Forward Head Posture" },
      { id: "herniated-disc", title: "Herniated disc" },
      { id: "kyphosis", title: "Kyphosis" },
      { id: "lordosis", title: "Lordosis" },
      { id: "neck-pain", title: "Neck Pain" },
      { id: "spondylolithesis", title: "Spondylolithesis" },
      { id: "stenosis", title: "Stenosis" },
      { id: "subluxation", title: "Subluxation" },
    ],
  },
  {
    id: "pelvis",
    title: "Pelvis",
    subItems: [
      {
        id: "psoas-hip-flexor-tightness",
        title: "Psoas & Hip Flexor Tightness",
      },
    ],
  },
  {
    id: "shoulder",
    title: "Shoulder",
    subItems: [
      { id: "adhesive-capsulitis", title: "Adhesive Capsulitis" },
      { id: "impingement", title: "Impingement" },
      { id: "rotator-cuff-injury", title: "Rotator Cuff Injury" },
    ],
  },
  {
    id: "thoracic",
    title: "Thoracic",
    subItems: [
      { id: "bulging-disc", title: "Bulging disc" },
      { id: "degenerated-disc", title: "Degenerated disc" },
      { id: "facet-syndrome", title: "Facet Syndrome" },
      { id: "herniated-disc", title: "Herniated disc" },
      { id: "kyphosis", title: "Kyphosis" },
      { id: "lordosis", title: "Lordosis" },
      { id: "scoliosis", title: "Scoliosis" },
      { id: "spondylolithesis", title: "Spondylolithesis" },
      { id: "stenosis", title: "Stenosis" },
      { id: "subluxation", title: "Subluxation" },
      { id: "thoracic-pain", title: "Thoracic Pain" },
    ],
  },
  {
    id: "wrist",
    title: "Wrist",
    subItems: [{ id: "carpal-tunnel", title: "Carpal Tunnel" }],
  },
];
